### ISSUE TITLE
Use consistent names for each fighter

### ISSUE THREAD

**Issue by btk5h** [marcrd/smash-ultimate-assets#8]
Currently, there are a few fighters whose portraits and stock icons are listed under their romanized Japanese names instead of their English names. For consistency, these files should be renamed.

`gaogaen` => `incineroar`
`shizue` => `isabelle`
`packun_flower` => `piranha_plant`

**Comment by marcrd** [comment]
Good point, definitely can get to that renaming this week unless you get to it before me!

**Comment by marcrd** [comment]
Closed by https://github.com/marcrd/smash-ultimate-assets/pull/10
